# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# AddFields_Convert2Int.py
# Created on: 2016-11-29 09:57:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
FST_Thiess = "FST_Thiessen"

# ### rmsMin
# ### rmsMax

# ### rmsRng
# Process: Add Field
arcpy.AddField_management(FST_Thiess, "rmsRngInt", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
# Process: Calculate Field 
arcpy.CalculateField_management(FST_Thiess, "rmsRngInt", "Int ( [rmsRng]*10000 )", "VB", "")

# ### currAbsMin
# Process: Add Field
arcpy.AddField_management(FST_Thiess, "cAbsMinInt", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
# Process: Calculate Field
arcpy.CalculateField_management(FST_Thiess, "cAbsMinInt", "Int ( [currAbsMin]*1000000 )", "VB", "")

# ### currAbsMax
# Process: Add Field
arcpy.AddField_management(FST_Thiess, "cAbsMaxInt", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
# Process: Calculate Field
arcpy.CalculateField_management(FST_Thiess, "cAbsMaxInt", "Int ( [currAbsMax]*1000000 )", "VB", "")

# ### currAbsRng
# Process: Add Field
arcpy.AddField_management(FST_Thiess, "cAbsRngInt", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
# Process: Calculate Field
arcpy.CalculateField_management(FST_Thiess, "cAbsRngInt", "Int ( [currAbsRng]*1000000 )", "VB", "")

# ### currNetMin
# Process: Add Field
arcpy.AddField_management(FST_Thiess, "cNetMinInt", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
# Process: Calculate Field
arcpy.CalculateField_management(FST_Thiess, "cNetMinInt", "Int ( [currNetMin]*1000000 )", "VB", "")

# ### currNetMax
# Process: Add Field
arcpy.AddField_management(FST_Thiess, "cNetMaxInt", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
# Process: Calculate Field
arcpy.CalculateField_management(FST_Thiess, "cNetMaxInt", "Int ( [currNetMax]*1000000 )", "VB", "")

# ### currNetRng
# Process: Add Field
arcpy.AddField_management(FST_Thiess, "cNetRngInt", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
# Process: Calculate Field
arcpy.CalculateField_management(FST_Thiess, "cNetRngInt", "Int ( [currNetRng]*1000000 )", "VB", "")

# ### stressRng
# Process: Add Field
arcpy.AddField_management(FST_Thiess, "strsRngInt", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
# Process: Calculate Field
arcpy.CalculateField_management(FST_Thiess, "strsRngInt", "Int ( [stressRng]*1000000 )", "VB", "")

# ### tide
# Process: Add Field
arcpy.AddField_management(FST_Thiess, "tideInt", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")
# Process: Calculate Field
arcpy.CalculateField_management(FST_Thiess, "tideInt", "Int ( [tide]*1000000 )", "VB", "")
